### ISSUE TITLE
Problemas com módulo stimer.c

### ISSUE THREAD

**Issue by fabricio-godoi** [brtos/brtos#14]
Olá a todos,

Utilizando o módulo stimer.c acabei encontrando alguns problemas.

1- Ao utilizar a função OSTimerStop ao deletar um temporizador o status do timer vai para TIMER_NOT_ALLOCATED, o que não permite utilizar a função OSTimerSet novamente, a qual atualmente é a única forma de resetar o timer além da função OSTimerInit que instancia a task do timer. Por simplicidade no que estou usando, atualizei para TIMER_NOT_USED nessa função e dentro do BRTOSTimerTask, permitindo a reutilização do timer. Estaria correto fazer isso?

2- Na função "Descer" acabei me deparando com problema de ponteiro ao acessar o "timers[son]" na linha 86. Como não consegui compreender completamente essa parte do código, evitei o erro verificando se o ponteiro não era nulo -> if ((son <= n && timers[son] != NULL && timers[i] != NULL)&& (timers[son]->timeout < timers[i]->timeout)). Após isso, não tive outro problema ate o momento.

3- Na função BRTOSTimerTask adicionei "p->state = TIMER_STOPPED;" antes de acessar a função de callback configurada, pois se for utilizada a função OSTimerGet dentro da função de callback, o timer não necessariamente pode retornar como STOPPED, e introduzindo esse estado simplifica o sistema de verificação no callback caso necessário.

Obrigado!

Att. Fabrício

**Comment by AngelPortal** [comment]
Ola Fabricio
Recebi sua notificação, mas não ficou claro em que situação foi necessária estas modificações.
Outro dia descobri um port do FreeRTOS para Arduino UNO. Já existe um port
do BRTOS em forma de um Sketch arduino UNO ou Leonardo para realizar projetos também!!!!

**Comment by barriquello** [comment]
Olá Fabrício, com relação aos itens 2 e 3 suas correções estão adequadas. Mas no item 3 deve-se reajustar o estado do timer para TIMER_RUNNING caso a função de callback retorne repeat > 0, pois neste caso o timer será reiniciado. Já com relação ao item 1, de fato tem um erro no código em todas as linhas onde o timer deveria ser apagado, pois o timer deveria ser colocado no estado TIMER_NOT_USED nas linhas onde consta  p->state = TIMER_NOT_ALLOCATED.  Fique à vontade para fazer um pull request com as correções. Obrigado.

**Comment by barriquello** [comment]
Olá AngelPortal, o BRTOS possui port para o microcontrolador ATMEGA do Arduino aqui: https://github.com/brtos/brtos/tree/master/hal/Atmel_Studio_6_ATMEGA. Porém, está no formato do Atmel Studio e não como sketch, mas você pode usá-lo ao importar seu sketch usando o Atmel Studio (https://www.youtube.com/watch?v=7WnOe00dVu0). Caso você queira contribuir um sketch com o port do BRTOS, sua contribuição é muito bem vinda.

**Comment by barriquello** [comment]
Olá Fabrício, não há problema de o contador chegar a zero. Mas realmente ele não deve ser decrementado quando estiver valendo 0. Talvez valha a pena testar se é maior que zero, antes de decrementar para evitar underflow. De fato, isto não deveria ocorrer, pois só é decrementado quando há algum timer na lista. Todavia, não vejo problema em adicionar esta proteção a mais.
