### ISSUE TITLE
Organizing the HAL drivers

### ISSUE THREAD

**Issue by miguelmoreto** [brtos/brtos#2]
Hello, I have an enhancement suggestion concerning the BRTOS HAL drivers.

There is no "standard" HAL, the user have to select one "by hand". With SVN version control this was easy to achieve, just set two local repositories: one for BRTOS kernel and another for the chosen HAL. 

Now, with GIT, this scheme will not work, the user will have to delete the other HALs... kind of confusing and messy. Therefore, I have a suggestion:

All the HAL drivers should be included in the project but with different file names (like HAL_GCC_CORTEX-M4.c and HAL_GCC_CORTEX-M4.h. The user just have to setup a #define in BRTOSConfig.h (or another header file) in order to choose the HAL needed. Depending on this define only the correct HAL files are included.

What do you think? Is this a valid idea?

**Comment by barriquello** [comment]
Dear miguelmoreto,

I understand your point. However, I think this solution would require including a C file (*.c) in another C source file, which is weird and may not work in some IDEs. Also, it breaks the compatibility with older versions of BRTOS.

I think the easiest solution by now is to use GIT as one would do with SVN, i.e. selecting the files you want to checkout. See the example below:

mkdir brtos_project
cd brtos_project
git init 
git fetch https://github.com/brtos/brtos.git
git checkout FETCH_HEAD brtos/
git checkout FETCH_HEAD hal/GCC_CORTEX-M4/

In this way, GIT will only check out the files for brtos core and the hal files for the ARM Cortex-M4 for GCC compiler.
