### ISSUE TITLE
Sugestões de melhorias: TIPOS

### ISSUE THREAD

**Issue by barriquello** [brtos/brtos#4]
Legenda: x - Pronto, D- em discussão, E - em andamento, C - cancelado, T - falta testar

## Tipos:

* [D] o arquivo OS_types.h deve ser removido e os tipos definidos em HAL.h, pois devem ser portados corretamente. Motivo: pode ser causa de bugs. Aumentar portabilidade

* [D] trocar os nomes dos tipos inteiros para os nomes dos tipos da biblioteca padrão do C99 - stdint.h. Motivo: Usar padrão C. Facilita portabilidade.

* [D] definir um tipo stack_pointer_t ao invés de usar a macro SP_SIZE. Este tipo deve estar no port (HAL.h). Motivo: o código fica menos poluído.

**Comment by gustavowd** [comment]
Que acha do tipo stack pointer ser um unsigned int para todos os ports? Me parece que o tipo se adapta a qualquer situação.

Quanto aos tipos, podemos substituir diretamente pelos tipos do stdint.h e stdbool.h do c:
BOOLEAN --> bool
CHAR8 --> char
INT8U --> uint8_t
INT8S --> int8_t
INT16U --> uint16_t
INT16S --> int16_t
INT32U --> uint32_t
INT32S --> int32_t

**Comment by barriquello** [comment]
Com relação aos tipos e ao stack pointer me parece ok. Apenas no caso do compilador não ter suporte ao C99, os tipos devem ser definidos no hal.h. Então, pode-se incluir stdbool.h e stdint.h no hal.h, e deixar um define para desabilitar a inclusão no caso do compilador não ter o suporte ao C99.
