### ISSUE TITLE
Sugestões de melhorias: OBJETOS (semáforo, mailbox, fila e mutex)

### ISSUE THREAD

**Issue by barriquello** [brtos/brtos#5]
Legenda: x - Pronto, D- em discussão, E - em andamento, C - cancelado, T - falta testar

## Filas:

* [T] Integrar a estrutura da fila com a estrutura do evento. Deixar oculta ao usuário a declaração da estrutura de fila. Motivo: facilidade de uso.

## Mailbox:

* [D] Remover. Motivo: pouco uso. Pode-se usar uma fila com tamanho de ponteiro para a mesma função.

**Comment by gustavowd** [comment]
A estrutura de fila agora é associada internamente na função create para as filas estáticas ou alocada dinamicamente nas filas dinâmicas. As filas de 16 e 32 que não fazem uso de eventos deixaram de solicitar uma estrutura de evento na sua criação.
